/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewRouteImport } from './routes/new'
import { Route as ModChatsRouteImport } from './routes/mod-chats'
import { Route as ModRouteImport } from './routes/mod'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BestMembersRouteImport } from './routes/best-members'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertisementRouteImport } from './routes/advertisement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as ModChatIdRouteImport } from './routes/mod-chat.$id'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModChatsRoute = ModChatsRouteImport.update({
  id: '/mod-chats',
  path: '/mod-chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ModRoute = ModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BestMembersRoute = BestMembersRouteImport.update({
  id: '/best-members',
  path: '/best-members',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisementRoute = AdvertisementRouteImport.update({
  id: '/advertisement',
  path: '/advertisement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModChatIdRoute = ModChatIdRouteImport.update({
  id: '/mod-chat/$id',
  path: '/mod-chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertisement': typeof AdvertisementRoute
  '/auth': typeof AuthRoute
  '/best-members': typeof BestMembersRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/mod': typeof ModRoute
  '/mod-chats': typeof ModChatsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/c/$slug': typeof CSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/mod-chat/$id': typeof ModChatIdRoute
  '/t/$slug': typeof TSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertisement': typeof AdvertisementRoute
  '/auth': typeof AuthRoute
  '/best-members': typeof BestMembersRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/mod': typeof ModRoute
  '/mod-chats': typeof ModChatsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/c/$slug': typeof CSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/mod-chat/$id': typeof ModChatIdRoute
  '/t/$slug': typeof TSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertisement': typeof AdvertisementRoute
  '/auth': typeof AuthRoute
  '/best-members': typeof BestMembersRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/messages': typeof MessagesRoute
  '/mod': typeof ModRoute
  '/mod-chats': typeof ModChatsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/c/$slug': typeof CSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/mod-chat/$id': typeof ModChatIdRoute
  '/t/$slug': typeof TSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertisement'
    | '/auth'
    | '/best-members'
    | '/bookmarks'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/leaderboard'
    | '/messages'
    | '/mod'
    | '/mod-chats'
    | '/new'
    | '/notifications'
    | '/rules'
    | '/settings'
    | '/support'
    | '/c/$slug'
    | '/marketplace/$slug'
    | '/mod-chat/$id'
    | '/t/$slug'
    | '/u/$username'
    | '/marketplace/'
    | '/api/public/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advertisement'
    | '/auth'
    | '/best-members'
    | '/bookmarks'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/leaderboard'
    | '/messages'
    | '/mod'
    | '/mod-chats'
    | '/new'
    | '/notifications'
    | '/rules'
    | '/settings'
    | '/support'
    | '/c/$slug'
    | '/marketplace/$slug'
    | '/mod-chat/$id'
    | '/t/$slug'
    | '/u/$username'
    | '/marketplace'
    | '/api/public/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertisement'
    | '/auth'
    | '/best-members'
    | '/bookmarks'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/leaderboard'
    | '/messages'
    | '/mod'
    | '/mod-chats'
    | '/new'
    | '/notifications'
    | '/rules'
    | '/settings'
    | '/support'
    | '/c/$slug'
    | '/marketplace/$slug'
    | '/mod-chat/$id'
    | '/t/$slug'
    | '/u/$username'
    | '/marketplace/'
    | '/api/public/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdvertisementRoute: typeof AdvertisementRoute
  AuthRoute: typeof AuthRoute
  BestMembersRoute: typeof BestMembersRoute
  BookmarksRoute: typeof BookmarksRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MessagesRoute: typeof MessagesRoute
  ModRoute: typeof ModRoute
  ModChatsRoute: typeof ModChatsRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  CSlugRoute: typeof CSlugRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  ModChatIdRoute: typeof ModChatIdRoute
  TSlugRoute: typeof TSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-chats': {
      id: '/mod-chats'
      path: '/mod-chats'
      fullPath: '/mod-chats'
      preLoaderRoute: typeof ModChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod': {
      id: '/mod'
      path: '/mod'
      fullPath: '/mod'
      preLoaderRoute: typeof ModRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-members': {
      id: '/best-members'
      path: '/best-members'
      fullPath: '/best-members'
      preLoaderRoute: typeof BestMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertisement': {
      id: '/advertisement'
      path: '/advertisement'
      fullPath: '/advertisement'
      preLoaderRoute: typeof AdvertisementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-chat/$id': {
      id: '/mod-chat/$id'
      path: '/mod-chat/$id'
      fullPath: '/mod-chat/$id'
      preLoaderRoute: typeof ModChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdvertisementRoute: AdvertisementRoute,
  AuthRoute: AuthRoute,
  BestMembersRoute: BestMembersRoute,
  BookmarksRoute: BookmarksRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  MessagesRoute: MessagesRoute,
  ModRoute: ModRoute,
  ModChatsRoute: ModChatsRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  CSlugRoute: CSlugRoute,
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  ModChatIdRoute: ModChatIdRoute,
  TSlugRoute: TSlugRoute,
  UUsernameRoute: UUsernameRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
